{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}

{{- range $job := .Values.jobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $job.name }}-ingestion
spec:
  concurrencyPolicy: Forbid
  schedule: {{ $job.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: {{ $job.name }}-ingestion
            image: "{{ $job.image.repository }}:{{ $job.image.tag }}"
            {{- with $job.args }}
            args:
{{ toYaml . | indent 12 }}
            {{- end }}
            volumeMounts:
            - name: ingestion-secrets
              mountPath: /var/secrets
          {{- with $job.volumes }}
          volumes:
{{ toYaml . | indent 10 }}
          {{- end }}
{{- end }}